# Subscribers.
opt_graph_topic:             /graph_monitor/sparse_graph/graph
opt_traj_topic:              /graph_monitor/sparse_graph/trajectory
est_traj_topic:              /trajectory
est_traj_path_topic:         /incremental_trajectory
opt_submap_constraint_topic: /graph_monitor/submaps

# Publishers.
anchor_node_topic:           '/graph_client/anchor_nodes'
relative_node_topic:         '/graph_client/relative_nodes'
intra_constraints:           '/graph_client/intra_constraints'
verification_service:        '/graph_monitor/verification'

# Subscriber and Publisher
client_update_topic:         "/graph_client/latest_graph"

# Div
# dataroot:                  "/home/subt/mapping_ws/src/fgsp"
dataroot:                    "/home/berlukas/Documents/workspace/fgsp_ws/src/fgsp"
# robot_name:                "anymal_1"
robot_name:                  "cerberus"
random_forest_model:         "/config/forest.joblib"
update_rate:                 0.02
enable_anchor_constraints:   True
enable_submap_constraints:   True
enable_signal_recording:     True
signal_export_path:          "/data/{key}_{src}_signal.npy"
enable_trajectory_recording: True
trajectory_export_path:      "/data/{key}_{src}_trajectory.npy"
