graph_topic:          /graph_monitor/sparse_graph/graph
traj_opt_topic:       /graph_monitor/sparse_graph/trajectory
traj_topic:           /trajectory

update_rate:          0.2

random_forest_model:  "/home/berlukas/Documents/workspace/fgsp_ws/src/fgsp/config/forest.joblib"
update_good_topic:    '/graph_client/anchor_nodes'
update_bad_topic:     '/graph_client/update_nodes'
