# Subscribers.
graph_topic:                 /graph_monitor/sparse_graph/graph
traj_opt_topic:              /graph_monitor/sparse_graph/trajectory
traj_topic:                  /trajectory
traj_path_topic:             /incremental_trajectory
submap_constraint_topic:     /graph_monitor/submaps

# Publishers.
anchor_node_topic:           '/graph_client/anchor_nodes'
relative_node_topic:         '/graph_client/relative_nodes'
intra_constraints:           '/graph_client/intra_constraints'

verification_service:        '/grap_monitor/verification'


# Div
dataroot:                    "/home/subt/mapping_ws/src/fgsp"
#dataroot:                   "/home/berlukas/Documents/workspace/fgsp_ws/src/fgsp"
robot_name:                  "anymal_1"
random_forest_model:         "/config/forest.joblib"
update_rate:                 0.2
client_update_topic:         "/graph_client/latest_graph"
enable_anchor_constraints:   True
enable_submap_constraints:   True
enable_signal_recording:     True
signal_export_path:          "/data/{key}_{src}_signal.npy"
enable_trajectory_recording: True
trajectory_export_path:      "/data/{key}_{src}_trajectory.npy"
