cloud_publisher:
  ros__parameters:
    cloud_topic: "/ply_cloud"
    cloud_input_path: "/media/berlukas/Data/data/datasets/fgsp/results/v2/darpa_artifact_img/clouds/"

    path_topic: "/path"
    path_input_path: "/media/berlukas/Data/data/datasets/fgsp/results/v2/darpa_artifact_img/paths/"

    rate: 0.1
    use_voxel_grid: False
    voxel_size: 0.15
