objects:
  - type: cell_phone
    position: [28.716, 56.422, 0.396]
  - type: cell_phone
    position: [25.8545, 57.2535, -3.5634]
  - type: cell_phone
    position: [24.1107, 57.7283, -1.7493]
