path_transformer:
  ros__parameters:
    input_path: "/media/berlukas/Data/data/datasets/fgsp/results/v2/darpa_finals/anymal_4/compslam.csv"
    export_path: "/tmp/transformed.npy"

    T:
      [
        0.999960,
        0.004036,
        0.007961,
        0.018325,
        -0.003881,
        0.999806,
        -0.019309,
        0.021186,
        -0.008037,
        0.019277,
        0.999782,
        0.101594,
        0.000000,
        0.000000,
        0.000000,
        1.000000,
      ]
