reproject_viz:
  ros__parameters:
    dataroot: "/media/berlukas/Data/data/datasets/fgsp/results/v2/hagerbach/anymal_2/"
    gt_traj_file: "gt.csv"
    est_traj_file: "onboard.csv"
    corr_traj_file: "corrected_hierarchy_3.csv"
    constraints_file: "opt_labels.dat"
    connections_file: "opt_connections.dat"

    cloud_in: "/point_cloud_filter/lidar/point_cloud_filtered"
    skip_every_nth: 3

    enable_gt: True
    enable_est: False
    enable_corr: True
    enable_graph: False

    graph_coords_file: "data/opt_graph_coords.npy"
    hierarchy_levels: 1
    z_offset: 10.0

    compute_splines: False
    spline_points: 10
    spline_low_height: 1
    spline_mid_height: 4
    spline_large_height: 7

    T_GT_EST:
      [
        0.918835,
        -0.394608,
        -0.005173,
        1.077152,
        0.394460,
        0.918731,
        -0.018294,
        -0.268902,
        0.011971,
        0.014769,
        0.999819,
        -0.428035,
        0.000000,
        0.000000,
        0.000000,
        1.000000,
      ]

    T_GT_CORR:
      [
        0.90748787,
        -0.4199247,
        0.01135842,
        1.06843516,
        0.42005013,
        0.90740832,
        -0.0129626,
        0.31985667,
        -0.00486341,
        0.01653451,
        0.99985147,
        -0.48456108,
        0.,
        0.,
        0.,
        1.,
      ]
