simulation:
  ros__parameters:
    server_file: "/media/berlukas/Data/data/datasets/fgsp/results/v2/seemuehle_img/paths/anymal_2.csv"
    # robot_file: "/home/berlukas/Documents/workspace/darpa/src/trajectory_eval/Trajectories/1_cerberus/2_compslam_post/compslam_post_tum.csv"

    robot_name: "anymal_2"
    map_frame: "map"
    child_frame: "base"
    graph_threshold_dist: 20.0

    odom_topic: "/odometry"
    monitor_topic: "/graph_monitor/sparse_graph/trajectory"

    out_bag_file: "/tmp/odom_and_monitor.bag"
